// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type ActivityLog struct {
	ID        int64      `json:"id"`
	JobID     string     `json:"job_id"`
	Date      time.Time  `json:"date"`
	Action    string     `json:"action"`
	Notes     *string    `json:"notes"`
	CreatedAt *time.Time `json:"created_at"`
}

type Artifact struct {
	ID          int64      `json:"id"`
	JobID       string     `json:"job_id"`
	Type        string     `json:"type"`
	Filepath    string     `json:"filepath"`
	ProfileHash string     `json:"profile_hash"`
	Stale       int64      `json:"stale"`
	CreatedAt   *time.Time `json:"created_at"`
}

type Job struct {
	ID            string     `json:"id"`
	Company       string     `json:"company"`
	Role          string     `json:"role"`
	Stage         string     `json:"stage"`
	Verdict       string     `json:"verdict"`
	Salary        *string    `json:"salary"`
	SalaryMin     *int64     `json:"salary_min"`
	Remote        *string    `json:"remote"`
	Source        *string    `json:"source"`
	SourceUrl     *string    `json:"source_url"`
	RawJd         *string    `json:"raw_jd"`
	Added         time.Time  `json:"added"`
	LastActivity  time.Time  `json:"last_activity"`
	FitScore      *int64     `json:"fit_score"`
	Summary       *string    `json:"summary"`
	Positives     *string    `json:"positives"`
	Concerns      *string    `json:"concerns"`
	MyNotes       *string    `json:"my_notes"`
	CompanyValues *string    `json:"company_values"`
	Networking    *string    `json:"networking"`
	RoleDetails   *string    `json:"role_details"`
	CreatedAt     *time.Time `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
}

type UserProfile struct {
	ID                int64      `json:"id"`
	ResumeMd          string     `json:"resume_md"`
	CoverLetterSample *string    `json:"cover_letter_sample"`
	SalaryMin         *int64     `json:"salary_min"`
	SalaryMax         *int64     `json:"salary_max"`
	SalaryTarget      *int64     `json:"salary_target"`
	RemotePref        *string    `json:"remote_pref"`
	Location          *string    `json:"location"`
	Industries        *string    `json:"industries"`
	GreenFlags        *string    `json:"green_flags"`
	RedFlags          *string    `json:"red_flags"`
	TechPrefs         *string    `json:"tech_prefs"`
	WritingVoiceMd    *string    `json:"writing_voice_md"`
	ProfileHash       string     `json:"profile_hash"`
	UpdatedAt         *time.Time `json:"updated_at"`
}
