// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createActivityEntry = `-- name: CreateActivityEntry :one
INSERT INTO activity_log (job_id, date, action, notes)
VALUES (?, ?, ?, ?)
RETURNING id, job_id, date, "action", notes, created_at
`

type CreateActivityEntryParams struct {
	JobID  string    `json:"job_id"`
	Date   time.Time `json:"date"`
	Action string    `json:"action"`
	Notes  *string   `json:"notes"`
}

func (q *Queries) CreateActivityEntry(ctx context.Context, arg CreateActivityEntryParams) (ActivityLog, error) {
	row := q.db.QueryRowContext(ctx, createActivityEntry,
		arg.JobID,
		arg.Date,
		arg.Action,
		arg.Notes,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Date,
		&i.Action,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (job_id, type, filepath, profile_hash)
VALUES (?, ?, ?, ?)
RETURNING id, job_id, type, filepath, profile_hash, stale, created_at
`

type CreateArtifactParams struct {
	JobID       string `json:"job_id"`
	Type        string `json:"type"`
	Filepath    string `json:"filepath"`
	ProfileHash string `json:"profile_hash"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.JobID,
		arg.Type,
		arg.Filepath,
		arg.ProfileHash,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.Filepath,
		&i.ProfileHash,
		&i.Stale,
		&i.CreatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  id, company, role, stage, verdict, salary, salary_min, remote,
  source, source_url, raw_jd, added, last_activity, fit_score,
  summary, positives, concerns, my_notes, company_values, networking, role_details
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, company, role, stage, verdict, salary, salary_min, remote, source, source_url, raw_jd, added, last_activity, fit_score, summary, positives, concerns, my_notes, company_values, networking, role_details, created_at, updated_at
`

type CreateJobParams struct {
	ID            string    `json:"id"`
	Company       string    `json:"company"`
	Role          string    `json:"role"`
	Stage         string    `json:"stage"`
	Verdict       string    `json:"verdict"`
	Salary        *string   `json:"salary"`
	SalaryMin     *int64    `json:"salary_min"`
	Remote        *string   `json:"remote"`
	Source        *string   `json:"source"`
	SourceUrl     *string   `json:"source_url"`
	RawJd         *string   `json:"raw_jd"`
	Added         time.Time `json:"added"`
	LastActivity  time.Time `json:"last_activity"`
	FitScore      *int64    `json:"fit_score"`
	Summary       *string   `json:"summary"`
	Positives     *string   `json:"positives"`
	Concerns      *string   `json:"concerns"`
	MyNotes       *string   `json:"my_notes"`
	CompanyValues *string   `json:"company_values"`
	Networking    *string   `json:"networking"`
	RoleDetails   *string   `json:"role_details"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.Company,
		arg.Role,
		arg.Stage,
		arg.Verdict,
		arg.Salary,
		arg.SalaryMin,
		arg.Remote,
		arg.Source,
		arg.SourceUrl,
		arg.RawJd,
		arg.Added,
		arg.LastActivity,
		arg.FitScore,
		arg.Summary,
		arg.Positives,
		arg.Concerns,
		arg.MyNotes,
		arg.CompanyValues,
		arg.Networking,
		arg.RoleDetails,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Stage,
		&i.Verdict,
		&i.Salary,
		&i.SalaryMin,
		&i.Remote,
		&i.Source,
		&i.SourceUrl,
		&i.RawJd,
		&i.Added,
		&i.LastActivity,
		&i.FitScore,
		&i.Summary,
		&i.Positives,
		&i.Concerns,
		&i.MyNotes,
		&i.CompanyValues,
		&i.Networking,
		&i.RoleDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
UPDATE jobs SET stage = 'Won''t Apply', updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, company, role, stage, verdict, salary, salary_min, remote, source, source_url, raw_jd, added, last_activity, fit_score, summary, positives, concerns, my_notes, company_values, networking, role_details, created_at, updated_at FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Stage,
		&i.Verdict,
		&i.Salary,
		&i.SalaryMin,
		&i.Remote,
		&i.Source,
		&i.SourceUrl,
		&i.RawJd,
		&i.Added,
		&i.LastActivity,
		&i.FitScore,
		&i.Summary,
		&i.Positives,
		&i.Concerns,
		&i.MyNotes,
		&i.CompanyValues,
		&i.Networking,
		&i.RoleDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, resume_md, cover_letter_sample, salary_min, salary_max, salary_target, remote_pref, location, industries, green_flags, red_flags, tech_prefs, writing_voice_md, profile_hash, updated_at FROM user_profile WHERE id = 1
`

func (q *Queries) GetProfile(ctx context.Context) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfile)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.ResumeMd,
		&i.CoverLetterSample,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryTarget,
		&i.RemotePref,
		&i.Location,
		&i.Industries,
		&i.GreenFlags,
		&i.RedFlags,
		&i.TechPrefs,
		&i.WritingVoiceMd,
		&i.ProfileHash,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivityLog = `-- name: ListActivityLog :many
SELECT id, job_id, date, "action", notes, created_at FROM activity_log WHERE job_id = ? ORDER BY date DESC, id DESC
`

func (q *Queries) ListActivityLog(ctx context.Context, jobID string) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLog, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Date,
			&i.Action,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, job_id, type, filepath, profile_hash, stale, created_at FROM artifacts WHERE job_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListArtifacts(ctx context.Context, jobID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifacts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Type,
			&i.Filepath,
			&i.ProfileHash,
			&i.Stale,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, company, role, stage, verdict, salary, salary_min, remote, source, source_url, raw_jd, added, last_activity, fit_score, summary, positives, concerns, my_notes, company_values, networking, role_details, created_at, updated_at FROM jobs ORDER BY
  CASE verdict WHEN 'green' THEN 0 WHEN 'yellow' THEN 1 ELSE 2 END,
  fit_score DESC,
  salary_min DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Role,
			&i.Stage,
			&i.Verdict,
			&i.Salary,
			&i.SalaryMin,
			&i.Remote,
			&i.Source,
			&i.SourceUrl,
			&i.RawJd,
			&i.Added,
			&i.LastActivity,
			&i.FitScore,
			&i.Summary,
			&i.Positives,
			&i.Concerns,
			&i.MyNotes,
			&i.CompanyValues,
			&i.Networking,
			&i.RoleDetails,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArtifactsStale = `-- name: MarkArtifactsStale :exec
UPDATE artifacts SET stale = 1
WHERE profile_hash != (SELECT profile_hash FROM user_profile WHERE id = 1)
`

func (q *Queries) MarkArtifactsStale(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markArtifactsStale)
	return err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs SET
  stage         = COALESCE(?1, stage),
  verdict       = COALESCE(?2, verdict),
  salary        = COALESCE(?3, salary),
  salary_min    = COALESCE(?4, salary_min),
  fit_score     = COALESCE(?5, fit_score),
  summary       = COALESCE(?6, summary),
  positives     = COALESCE(?7, positives),
  concerns      = COALESCE(?8, concerns),
  my_notes      = COALESCE(?9, my_notes),
  last_activity = CURRENT_DATE,
  updated_at    = CURRENT_TIMESTAMP
WHERE id = ?10
RETURNING id, company, role, stage, verdict, salary, salary_min, remote, source, source_url, raw_jd, added, last_activity, fit_score, summary, positives, concerns, my_notes, company_values, networking, role_details, created_at, updated_at
`

type UpdateJobParams struct {
	Stage     *string `json:"stage"`
	Verdict   *string `json:"verdict"`
	Salary    *string `json:"salary"`
	SalaryMin *int64  `json:"salary_min"`
	FitScore  *int64  `json:"fit_score"`
	Summary   *string `json:"summary"`
	Positives *string `json:"positives"`
	Concerns  *string `json:"concerns"`
	MyNotes   *string `json:"my_notes"`
	ID        string  `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.Stage,
		arg.Verdict,
		arg.Salary,
		arg.SalaryMin,
		arg.FitScore,
		arg.Summary,
		arg.Positives,
		arg.Concerns,
		arg.MyNotes,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Stage,
		&i.Verdict,
		&i.Salary,
		&i.SalaryMin,
		&i.Remote,
		&i.Source,
		&i.SourceUrl,
		&i.RawJd,
		&i.Added,
		&i.LastActivity,
		&i.FitScore,
		&i.Summary,
		&i.Positives,
		&i.Concerns,
		&i.MyNotes,
		&i.CompanyValues,
		&i.Networking,
		&i.RoleDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO user_profile (
  id, resume_md, cover_letter_sample, salary_min, salary_max, salary_target,
  remote_pref, location, industries, green_flags, red_flags, tech_prefs,
  writing_voice_md, profile_hash, updated_at
) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  resume_md = excluded.resume_md,
  cover_letter_sample = excluded.cover_letter_sample,
  salary_min = excluded.salary_min,
  salary_max = excluded.salary_max,
  salary_target = excluded.salary_target,
  remote_pref = excluded.remote_pref,
  location = excluded.location,
  industries = excluded.industries,
  green_flags = excluded.green_flags,
  red_flags = excluded.red_flags,
  tech_prefs = excluded.tech_prefs,
  writing_voice_md = excluded.writing_voice_md,
  profile_hash = excluded.profile_hash,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, resume_md, cover_letter_sample, salary_min, salary_max, salary_target, remote_pref, location, industries, green_flags, red_flags, tech_prefs, writing_voice_md, profile_hash, updated_at
`

type UpsertProfileParams struct {
	ResumeMd          string  `json:"resume_md"`
	CoverLetterSample *string `json:"cover_letter_sample"`
	SalaryMin         *int64  `json:"salary_min"`
	SalaryMax         *int64  `json:"salary_max"`
	SalaryTarget      *int64  `json:"salary_target"`
	RemotePref        *string `json:"remote_pref"`
	Location          *string `json:"location"`
	Industries        *string `json:"industries"`
	GreenFlags        *string `json:"green_flags"`
	RedFlags          *string `json:"red_flags"`
	TechPrefs         *string `json:"tech_prefs"`
	WritingVoiceMd    *string `json:"writing_voice_md"`
	ProfileHash       string  `json:"profile_hash"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertProfile,
		arg.ResumeMd,
		arg.CoverLetterSample,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryTarget,
		arg.RemotePref,
		arg.Location,
		arg.Industries,
		arg.GreenFlags,
		arg.RedFlags,
		arg.TechPrefs,
		arg.WritingVoiceMd,
		arg.ProfileHash,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.ResumeMd,
		&i.CoverLetterSample,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryTarget,
		&i.RemotePref,
		&i.Location,
		&i.Industries,
		&i.GreenFlags,
		&i.RedFlags,
		&i.TechPrefs,
		&i.WritingVoiceMd,
		&i.ProfileHash,
		&i.UpdatedAt,
	)
	return i, err
}
